[versions]
jason = "3.2.1"
tuprolog = "4.1.1"
junit = "5.11.4"
assertj = "3.26.3"

[libraries]
jason-interpreter = { module = "io.github.jason-lang:jason-interpreter", version.ref = "jason" }
tuprolog-core = { module = "it.unibo.alice.tuprolog:2p-core", version.ref = "tuprolog" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }